version: "3.8"
services:
  database:
    image: databaseImage
    build: ./database
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
    - type: volume
      source: project-db
      target: /var/lib/mysql 

frontend:
  image: frontendImage
  build: ./frontend
  ports:
    - target: 5000
      published: 5000
  environment:
    - DATABASE_URI=${DATABASE_URI}
      SECRET_KEY=${SECRET_KEY}
    
backend:
  image: backendImage
  build: ./backend
  ports:
  - target: 5001
    published: 5001 

  nginx:
    image: nginx:latest
    ports:
     - target: 80
       published: 80
       protocol: tcp
    volumes:
     - type: bind
       source: ./nginx/nginx.conf
       target: /etc/nginx/nginx.conf
    depends_on:
       - frontend

volumes:
  project-db: