version: "3.8"
services:
  database:
    container_name: database
    build: ./database
    image: 1m0gen/project-database
    environment:
      DATABASE_URI: mysql+pymysql://root:password@mysql:3306/sqldatabase
      SECRET_KEY: ${SECRET_KEY}
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sqldatabase
    volumes:
    - type: volume
      source: project-db
      target: /var/lib/mysql

  frontend:
    container_name: frontend
    build: ./frontend
    image: 1m0gen/project-frontend
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      DATABASE_URI: mysql+pymysql://root:password@mysql:3306/sqldatabase
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - backend
      - database

  backend:
    container_name: backend
    build: ./backend
    image: 1m0gen/project-backend
    environment:
      DATABASE_URI: mysql+pymysql://root:password@mysql:3306/sqldatabase
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - database

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - frontend
            
volumes:
  project-db: