- hosts: localhost
  connection: local
  tasks:
  - name: Generate key pair
    openssh_keypair:
      path: ~/.ssh/ansible_id_rsa

- hosts: jenkins
  become: true
  roles:
  - jenkins
  - docker

- hosts: prod
  become: true
  roles:
  - docker

- hosts: test
  become: true
  roles:
  - docker